#!/bin/sh
# scaffold/scripts/lib/makefile.sh — Generate Makefile for the scaffolded solution

generate_makefile() {
  log_info "Generating Makefile..."

  MAKEFILE="${OUTPUT_DIR}/Makefile"

  cat > "${MAKEFILE}" <<'MAKEFILE_EOF'
# Makefile for {{SOLUTION_NAME}}
# Generated by .NET Project Scaffold
DOTNET    := dotnet
# Support both .sln (dotnet <10) and .slnx (dotnet 10+)
SOLUTION  := $(firstword $(wildcard {{SOLUTION_NAME}}.sln {{SOLUTION_NAME}}.slnx))
COVERAGE_THRESHOLD := 90

.PHONY: build test coverage lint clean sbom benchmark

## build: Compile all projects in Release mode
build:
	$(DOTNET) build $(SOLUTION) --configuration Release

## test: Run all test projects
test:
	$(DOTNET) test --solution $(SOLUTION) --configuration Release --no-build

## coverage: Run tests with code coverage; fail if below $(COVERAGE_THRESHOLD)%
## Uses MTP-native --coverage flag (required for TUnit / Microsoft.Testing.Platform).
coverage:
	@echo "Running tests with coverage..."
	$(DOTNET) test --solution $(SOLUTION) \
	  --coverage \
	  --coverage-output coverage.cobertura.xml \
	  --coverage-output-format cobertura \
	  --configuration Release \
	  --no-build 2>&1 | tee /tmp/.coverage-output || true
	@if grep -q "Zero tests ran\|No test is available" /tmp/.coverage-output 2>/dev/null; then \
	  echo "coverage: no tests found — failing at 0% (threshold $(COVERAGE_THRESHOLD)%)"; \
	  exit 1; \
	fi
	@# MTP writes coverage XML alongside each test binary; find the first one
	@COVERAGE_FILE=$$(find . -path "*/TestResults/coverage.cobertura.xml" | head -1); \
	if [ -z "$$COVERAGE_FILE" ]; then \
	  echo "coverage: coverage report not found (run make build first)"; \
	  exit 1; \
	fi; \
	LINE_RATE=$$(grep -o 'line-rate="[0-9.]*"' "$$COVERAGE_FILE" | head -1 | grep -o '[0-9.]*'); \
	PCT=$$(awk "BEGIN {printf \"%.0f\", $$LINE_RATE * 100}"); \
	echo "coverage: $${PCT}% (threshold: $(COVERAGE_THRESHOLD)%)"; \
	if [ "$$PCT" -lt "$(COVERAGE_THRESHOLD)" ]; then \
	  echo "FAIL: coverage $${PCT}% is below threshold $(COVERAGE_THRESHOLD)%"; \
	  exit 1; \
	fi; \
	echo "PASS: coverage $${PCT}% meets threshold"

## lint: Check code formatting; non-zero exit if violations found
lint:
	$(DOTNET) format $(SOLUTION) --verify-no-changes

## clean: Remove all build artifacts, coverage reports
clean:
	find . -type d \( -name bin -o -name obj -o -name TestResults \) -exec rm -rf {} + 2>/dev/null || true
	@echo "Clean complete."

## sbom: Generate Software Bill of Materials (CycloneDX JSON)
sbom:
	@command -v cyclonedx >/dev/null 2>&1 || \
	  $(DOTNET) tool install --global CycloneDX 2>/dev/null || true
	$(DOTNET) CycloneDX $(SOLUTION) --out sbom.cdx.json --json
	@echo "SBOM generated: sbom.cdx.json"

## benchmark: Run BenchmarkDotNet benchmarks (Release mode, opt-in)
## Only available when scaffold was run with --benchmarks flag.
benchmark:
	@if [ ! -d tests/Benchmarks ]; then \
	  echo "benchmark: tests/Benchmarks not found."; \
	  echo "Re-run the scaffold with --benchmarks to generate the benchmark project."; \
	  exit 1; \
	fi
	$(DOTNET) run --project tests/Benchmarks/{{SOLUTION_NAME}}.Benchmarks.csproj \
	  --configuration Release
MAKEFILE_EOF

  # Substitute solution name in generated Makefile
  sed -i "s/{{SOLUTION_NAME}}/${SOLUTION_NAME}/g" "${MAKEFILE}"

  log_info "Makefile generated: ${MAKEFILE}"
}
